SET DEFAULT TO C:\vpi_final 
CLEAR 
CLEAR EVENTS 
SET TALK OFF
SET STATUS OFF 
SET DELETED ON
SET SAFETY OFF 
SET DATE BRITISH
SET CENTURY ON
DO FORM vpi_form_run
READ events
CLEAR EVENTS
CLEAR WINDOWS
CLOSE DATABASES
QUIT